services:
  orchestrator:
    build: modules/ORCHESTRATOR/
    ports:
      - "${ROOTSHOOT_ORCHESTRATOR_PORT}:${ROOTSHOOT_ORCHESTRATOR_PORT}"
    environment:
      - ENV=${ENV}
      - PORT=${ROOTSHOOT_ORCHESTRATOR_PORT}
      - LOCALENV=${LOCALENV}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_EXPIRATION=${REDIS_EXPIRATION}
      - REDIS_KEY_HASH=${REDIS_KEY_HASH}
      - DISABLE_CACHE=${DISABLE_CACHE}
      - PROFILING_ENABLED=${PROFILING_ENABLED}
      - ROOTSHOOT_USERS_SERVICE=${ROOTSHOOT_SERVER}:${ROOTSHOOT_USERS_SERVICE_PORT}
      - ROOTSHOOT_GROUPS_SERVICE=${ROOTSHOOT_SERVER}:${ROOTSHOOT_GROUPS_SERVICE_PORT}
      - ROOTSHOOT_NOTES_SERVICE=${ROOTSHOOT_SERVER}:${ROOTSHOOT_NOTES_SERVICE_PORT}
      - ROOTSHOOT_RESPONSES_SERVICE=${ROOTSHOOT_SERVER}:${ROOTSHOOT_RESPONSES_SERVICE_PORT}
      - ROOTSHOOT_NOTIFICATIONS_SERVICE=${ROOTSHOOT_SERVER}:${ROOTSHOOT_NOTIFICATIONS_SERVICE_PORT}
      - ROOTSHOOT_CONNECTIONS_SERVICE=${ROOTSHOOT_SERVER}:${ROOTSHOOT_CONNECTIONS_SERVICE_PORT}
      - INTEGRATION_WEB_APP_HOST=
      - STAGING_WEB_APP_HOST=
      - CONVOX_INTEGRATION_DOMAIN=
      - CONVOX_STAGING_DOMAIN=
      - POSTHOG_API_KEY=
    command: /go/bin/api
    depends_on:
      - postgres
      - redis
    networks:
      - sr-network


  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - sr-network
    restart: unless-stopped
    command: redis-server --appendonly yes


  postgres:
    image: postgres:17.5-alpine
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - sr-network

volumes:
  postgres_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data/postgresql
  redis_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data/redis

networks:
  sr-network:
    driver: bridge

